import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistPixelfy = localFont({
  src: "./fonts/PixelfySans.ttf",
  variable: "--font-pixelfy-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistPixelfy.variable}`}>
        {children}
      </body>
    </html>
  );
}
